# Generated by Django 5.2.7 on 2025-10-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backendApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seasonstat",
            unique_together={("player", "season", "team")},
        ),
    ]
