# Generated by Django 5.2.7 on 2025-10-20 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendApp", "0002_alter_seasonstat_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="height",
        ),
        migrations.RemoveField(
            model_name="player",
            name="weight",
        ),
        migrations.CreateModel(
            name="PlayerGameStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_date", models.CharField(blank=True, max_length=20, null=True)),
                ("game_type", models.CharField(blank=True, max_length=100, null=True)),
                ("team", models.CharField(blank=True, max_length=100, null=True)),
                ("opponent", models.CharField(blank=True, max_length=100, null=True)),
                ("win", models.IntegerField(blank=True, null=True)),
                ("home", models.IntegerField(blank=True, null=True)),
                ("minutes", models.FloatField(blank=True, null=True)),
                ("points", models.FloatField(blank=True, null=True)),
                ("assists", models.FloatField(blank=True, null=True)),
                ("blocks", models.FloatField(blank=True, null=True)),
                ("steals", models.FloatField(blank=True, null=True)),
                ("fg_percent", models.FloatField(blank=True, null=True)),
                ("threepa", models.FloatField(blank=True, null=True)),
                ("threep", models.FloatField(blank=True, null=True)),
                ("threep_percent", models.FloatField(blank=True, null=True)),
                ("fta", models.FloatField(blank=True, null=True)),
                ("ft", models.FloatField(blank=True, null=True)),
                ("ft_percent", models.FloatField(blank=True, null=True)),
                ("total_rebounds", models.FloatField(blank=True, null=True)),
                ("personal_fouls", models.FloatField(blank=True, null=True)),
                ("turnovers", models.FloatField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_game_stats",
                        to="backendApp.player",
                    ),
                ),
            ],
            options={
                "ordering": ["game_date"],
            },
        ),
        migrations.DeleteModel(
            name="Prediction",
        ),
    ]
