# Generated by Django 5.2.7 on 2025-10-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendApp", "0003_remove_player_height_remove_player_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playergamestat",
            name="game_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
