# Generated by Django 5.2.7 on 2025-10-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendApp", "0004_alter_playergamestat_game_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playergamestat",
            name="game_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
