# Generated by Django 5.2.7 on 2025-10-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendApp", "0005_alter_playergamestat_game_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(max_length=100),
        ),
    ]
